# Generated by Django 2.2.4 on 2019-08-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190817_0250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='P',
        ),
    ]
