# Generated by Django 2.2.4 on 2019-10-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='userid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
