# Generated by Django 2.2.4 on 2019-10-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191016_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='userid',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
