# Generated by Django 2.2.4 on 2019-08-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='datee',
            field=models.DateTimeField(auto_now_add=True, verbose_name='S'),
        ),
    ]
