# Generated by Django 2.2.4 on 2019-08-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_test_description'),
        ('contact', '0003_remove_appointment_datee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=11)),
                ('age', models.FloatField()),
                ('sex', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('test', models.ManyToManyField(blank=True, related_name='user_favourite', to='services.Test')),
            ],
        ),
    ]
