# Generated by Django 2.2.4 on 2019-08-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_doctor_description'),
        ('contact', '0005_auto_20190821_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='doctor',
            field=models.ManyToManyField(blank=True, default=None, to='departments.Doctor'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='test',
            field=models.ManyToManyField(blank=True, default=None, to='services.Test'),
        ),
    ]
