# Generated by Django 2.2.4 on 2019-08-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_doctor_description'),
        ('contact', '0006_auto_20190821_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patients',
            name='doctor',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.Doctor'),
        ),
    ]
