# Generated by Django 2.2.4 on 2019-08-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_doctor_description'),
        ('contact', '0008_auto_20190821_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patients',
            name='doctor',
            field=models.ManyToManyField(blank=True, default=None, to='departments.Doctor'),
        ),
    ]
