# Generated by Django 2.2.4 on 2019-09-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20190903_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='test',
        ),
    ]
