# Generated by Django 2.2.4 on 2019-08-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Subtitle', models.CharField(max_length=40)),
                ('Description', models.TextField()),
                ('Publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Subtitle', models.CharField(max_length=40)),
                ('Description', models.TextField()),
                ('Publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Subtitle', models.CharField(max_length=40)),
                ('Description', models.TextField()),
                ('Publish', models.BooleanField(default=False)),
            ],
        ),
    ]
