# Generated by Django 2.2.4 on 2019-08-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190821_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
