# Generated by Django 2.2.4 on 2019-08-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='maintenance_mode',
        ),
    ]
