# Generated by Django 2.2.4 on 2019-08-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_siteconfiguration_maintenance_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Our Center', max_length=20)),
                ('Subtitle', models.CharField(max_length=30)),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name': 'Our Center',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Our Mission', max_length=20)),
                ('Subtitle', models.CharField(max_length=30)),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name': 'Our Mission',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Our Vision', max_length=20)),
                ('Subtitle', models.CharField(max_length=30)),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name': 'Our Vision',
            },
        ),
    ]
