# Generated by Django 2.2.4 on 2019-08-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Image',
            field=models.ImageField(upload_to='departments'),
        ),
    ]
