# Generated by Django 2.2.4 on 2019-08-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
